samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Controllers/CertificateController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using System.Web.Mvc;

namespace BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Controllers
{
    [Authorize]
    public class CertificateController : Controller
    {
        UserAccountService userAccountService;

        public CertificateController(UserAccountService userAccountService)
        {
            this.userAccountService = userAccountService;
        }

        public ActionResult Index()
        {
            var acct = userAccountService.GetByID(this.User.GetUserID());
            return View(acct);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string thumbprint)
        {
            var acct = userAccountService.GetByID(this.User.GetUserID());
            acct.RemoveCertificate(thumbprint);
            userAccountService.Update(acct);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add()
        {
            var acct = userAccountService.GetByID(this.User.GetUserID());

            if (Request.Files.Count == 0)
            {
                ModelState.AddModelError("", "No file uploaded");
            }
            else
            {
                try
                {
                    using (var ms = new MemoryStream())
                    {
                        Request.Files[0].InputStream.CopyTo(ms);
                        var bytes = ms.ToArray();

                        var cert = new X509Certificate2(bytes);
                        acct.AddCertificate(cert);
                        userAccountService.Update(acct);

                        return RedirectToAction("Index");
                    }
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Error processing certificate");
                }
            }

            return View("Index", acct);
        }
    }
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/Certificate/Index.cshtml
@model BrockAllen.MembershipReboot.UserAccount
@{
    ViewBag.Title = "Index";
}

@Html.ValidationSummary()

@using (Html.BeginForm("Add", "Certificate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>New Certificate</legend>
        <p>New Cert: <input type="file" name="cert" /></p>
        <p><button>Submit</button></p>
    </fieldset>
}

<h2>Existing Certs:</h2>
<ul>
    @foreach (var cert in Model.Certificates)
    {
        using (Html.BeginForm("Delete", "Certificate"))
        {
            @Html.AntiForgeryToken()
            <li>
                @cert.Subject
                <button name="thumbprint" value="@cert.Thumbprint">delete</button>
            </li>
        }
    }
</ul>