samples/CustomizationsSample/CustomizationsSample/Areas/UserAccount/Controllers/ChangeEmailController.cs
using BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Controllers
{
    [Authorize]
    public class ChangeEmailController : Controller
    {
        UserAccountService userAccountService;
        AuthenticationService authSvc;

        public ChangeEmailController(
            UserAccountService userAccountService, AuthenticationService authSvc)
        {
            this.userAccountService = userAccountService;
            this.authSvc = authSvc;
        }

        public ActionResult Index()
        {
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ChangeEmailRequestInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.ChangeEmailRequest(User.GetUserID(), model.NewEmail);
                    return View("ChangeRequestSuccess", (object)model.NewEmail);
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View("Index", model);
        }

        public ActionResult Confirm(string id)
        {
            var vm = new ChangeEmailFromKeyInputModel();
            vm.Key = id;
            return View("Confirm", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Confirm(ChangeEmailFromKeyInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (this.userAccountService.ChangeEmailFromKey(User.GetUserID(), model.Password, model.Key))
                    {
                        // since we've changed the email, we need to re-issue the cookie that
                        // contains the claims.
                        var account = this.userAccountService.GetByID(User.GetUserID());
                        authSvc.SignIn(account);
                        return View("Success");
                    }

                    ModelState.AddModelError("", "Error changing email.");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            
            return View("Confirm", model);
        }
    }
}

samples/CustomizationsSample/CustomizationsSample/Areas/UserAccount/Views/ChangeEmail/ChangeRequestSuccess.cshtml
@model string

@{
    ViewBag.Title = "ChangeRequestSuccess";
}

<h2>Registration Success</h2>
<p>
    You should recieve an email shortly at @Model.
    It will contain instructions to confirm your email change request.
</p>
<p>Thanks!</p>

samples/CustomizationsSample/CustomizationsSample/Areas/UserAccount/Views/ChangeEmail/Confirm.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.ChangeEmailFromKeyInputModel

@{
    ViewBag.Title = "Change Email";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("Error")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>

        @Html.EditorForModel()

        <div class="buttons">
            <button>Change Email</button>
        </div>
    </fieldset>
}

samples/CustomizationsSample/CustomizationsSample/Areas/UserAccount/Views/ChangeEmail/Index.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.ChangeEmailRequestInputModel
@{
    ViewBag.Title = "Change Email";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("Error")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>

        @Html.EditorForModel()

        <div class="buttons">
            <button>Change Email</button>
        </div>
    </fieldset>
}

@using (Html.BeginForm("Confirm", "ChangeEmail", FormMethod.Get))
{
    <fieldset>
        <legend>Confirm</legend>
        <p>
            <label for="id">Key</label>
            <input id="id" name="id" />
        </p>
        <p class="buttons"><button>Submit</button></p>
    </fieldset>
}

samples/CustomizationsSample/CustomizationsSample/Areas/UserAccount/Views/ChangeEmail/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>
<p>You email was successfully changed.</p>