samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Controllers/LoginController.cs
using BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models;
using System.ComponentModel.DataAnnotations;
using System.IdentityModel.Tokens;
using System.Security.Cryptography.X509Certificates;
using System.Web.Mvc;

namespace BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        UserAccountService userAccountService;
        AuthenticationService authSvc;

        public LoginController(AuthenticationService authSvc)
        {
            this.userAccountService = authSvc.UserAccountService;
            this.authSvc = authSvc;
        }

        public ActionResult Index()
        {
            return View(new LoginInputModel());
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginInputModel model)
        {
            if (ModelState.IsValid)
            {
                BrockAllen.MembershipReboot.UserAccount account;
                if (userAccountService.AuthenticateWithUsernameOrEmail(model.Username, model.Password, out account))
                {
                    authSvc.SignIn(account);

                    if (account.RequiresTwoFactorAuthCodeToSignIn)
                    {
                        return RedirectToAction("TwoFactorAuthCodeLogin");
                    }
                    if (account.RequiresTwoFactorCertificateToSignIn)
                    {
                        return RedirectToAction("CertificateLogin");
                    }
                    
                    if (userAccountService.IsPasswordExpired(account))
                    {
                        return RedirectToAction("Index", "ChangePassword");
                    }
                    
                    if (Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid Username or Password");
                }
            }

            return View(model);
        }

        public ActionResult TwoFactorAuthCodeLogin()
        {
            if (!User.HasUserID())
            {
                // if the temp cookie is expired, then make the login again
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TwoFactorAuthCodeLogin(string button, TwoFactorAuthInputModel model)
        {
            if (!User.HasUserID())
            {
                // if the temp cookie is expired, then make the login again
                return RedirectToAction("Index");
            }

            if (button == "signin")
            {
                if (ModelState.IsValid)
                {
                    BrockAllen.MembershipReboot.UserAccount account;
                    if (userAccountService.AuthenticateWithCode(this.User.GetUserID(), model.Code, out account))
                    {
                        authSvc.SignIn(account);

                        if (userAccountService.IsPasswordExpired(account))
                        {
                            return RedirectToAction("Index", "ChangePassword");
                        }

                        if (Url.IsLocalUrl(model.ReturnUrl))
                        {
                            return Redirect(model.ReturnUrl);
                        }

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Invalid Code");
                    }
                }
            }
            
            if (button == "resend")
            {
                this.userAccountService.SendTwoFactorAuthenticationCode(this.User.GetUserID());
            }

            return View("TwoFactorAuthCodeLogin", model);
        }

        public ActionResult CertificateLogin()
        {
            if (Request.ClientCertificate != null && 
                Request.ClientCertificate.IsPresent && 
                Request.ClientCertificate.IsValid)
            {
                try
                {
                    var cert = new X509Certificate2(Request.ClientCertificate.Certificate);
                    BrockAllen.MembershipReboot.UserAccount account;

                    var result = false;
                    // we're allowing the use of certs for login and for two factor auth. normally you'd 
                    // do only one or the other, but for the sake of the sample we're allowing both.
                    if (User.Identity.IsAuthenticated)
                    {
                        // this is when we're doing cert logins for two factor auth
                        result = this.authSvc.UserAccountService.AuthenticateWithCertificate(User.GetUserID(), cert, out account);
                    }
                    else
                    {
                        // this is when we're just doing certs to login (so no two factor auth)
                        result = this.authSvc.UserAccountService.AuthenticateWithCertificate(cert, out account);
                    }

                    if (result)
                    {
                        this.authSvc.SignIn(account, AuthenticationMethods.X509);

                        if (userAccountService.IsPasswordExpired(account))
                        {
                            return RedirectToAction("Index", "ChangePassword");
                        }

                        return RedirectToAction("Index", "Home");
                    }

                    ModelState.AddModelError("", "Invalid login");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            
            return View();
        }
    }
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Controllers/RegisterController.cs
using BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Controllers
{
    [AllowAnonymous]
    public class RegisterController : Controller
    {
        UserAccountService userAccountService;
        AuthenticationService authSvc;

        public RegisterController(AuthenticationService authSvc)
        {
            this.authSvc = authSvc;
            this.userAccountService = authSvc.UserAccountService;
        }

        public ActionResult Index()
        {
            return View(new RegisterInputModel());
        }
        
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Index(RegisterInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.CreateAccount(model.Username, model.Password, model.Email);
                    if (userAccountService.Configuration.RequireAccountVerification)
                    {
                        return View("Success", model);
                    }
                    else
                    {
                        return View("Confirm", true);
                    }
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(model);
        }

        public ActionResult Confirm(string id)
        {
            return View("Confirm");
        }

        [HttpPost]
        public ActionResult Confirm(string id, string password)
        {
            BrockAllen.MembershipReboot.UserAccount account;
            var result = this.userAccountService.VerifyAccount(id, password, out account);
            if (result)
            {
                authSvc.SignIn(account);
            }

            return RedirectToAction("ConfirmResult", new { success = result });
        }

        public ActionResult ConfirmResult(bool success)
        {
            return View("ConfirmResult", success);
        }

        public ActionResult Cancel(string id)
        {
            var result = this.userAccountService.CancelNewAccount(id);
            return View("Cancel", result);
        }
    }
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/Register/Cancel.cshtml
@model bool
@{
    ViewBag.Title = "Cancel";
}

@if (Model)
{
    <h2>Registration Cancelled</h2>
    <p>
        Your account has been closed.
        If you would like to re-register click @Html.ActionLink("here", "Index", "Register").
    </p>
    <p>Thanks!</p>
}
else
{
    <h2>There was an error canceling your account.</h2>
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/Register/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
}

@using(Html.BeginForm())
{
    <fieldset>
        <legend>Confirm Your Registration</legend>
        <p>
            @Html.Label("Re-enter your password")
            @Html.Password("password")
        </p>
        <p>
            <button>Submit</button>
        </p>
    </fieldset>
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/Register/ConfirmResult.cshtml
@model bool
@{
    ViewBag.Title = "Confirm";
}

@if (Model)
{
    <h2>Registration Confirmed</h2>
    <p>
        Your account is confirmed. You are now logged in.
    </p>
}
else
{
    <h2>Error confirming registration</h2>
    <p>
        There was an error confirming the registration. If you have already confirmed your account
        then you should recieve a confirmation email and should be able to login 
        @Html.ActionLink("here", "Index", "Login").
    </p>
    <p>
        If you would like to re-register click 
        @Html.ActionLink("here", "Index", "Register").
    </p>
}
<p>Thanks!</p>

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/Register/Index.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.RegisterInputModel
@{
    ViewBag.Title = "Register";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary("Please correct the following errors")
    @Html.AntiForgeryToken()

    <fieldset class="editor small">
        <legend>@ViewBag.Title</legend>

        @Html.EditorForModel()

        <div class="buttons">
            <button>Register</button>
        </div>

    </fieldset>
}

@using (Html.BeginForm("Confirm", "Register", FormMethod.Get))
{
    <fieldset>
        <legend>Confirm</legend>
        <p>
            <label for="id">Key</label>
            <input id="id" name="id" />
        </p>
        <p class="buttons"><button>Submit</button></p>
    </fieldset>
}

@using (Html.BeginForm("Cancel", "Register", FormMethod.Get))
{
    <fieldset>
        <legend>Cancel</legend>
        <p>
            <label for="id">Key</label>
            <input id="id" name="id" />
        </p>
        <p class="buttons"><button>Submit</button></p>
    </fieldset>
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/Register/Success.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.RegisterInputModel
@{
    ViewBag.Title = "Register";
}

<h2>Registration Success</h2>
<p>
    You should recieve an email shortly at @Model.Email. 
    It will contain instructions to verify your account 
    so that you can login.
</p>
<p>Thanks!</p>