samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Controllers/ChangeMobileController.cs
using BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Controllers
{
    [Authorize]
    public class ChangeMobileController : Controller
    {
        UserAccountService userAccountService;
        AuthenticationService authSvc;

        public ChangeMobileController(AuthenticationService authSvc)
        {
            this.userAccountService = authSvc.UserAccountService;
            this.authSvc = authSvc;
        }

        public ActionResult Index()
        {
            var acct = this.authSvc.UserAccountService.GetByID(User.GetUserID());
            return View("Index", new ChangeMobileRequestInputModel {Current = acct.MobilePhoneNumber });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string button, ChangeMobileRequestInputModel model)
        {
            if (button == "change")
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        this.userAccountService.ChangeMobilePhoneRequest(User.GetUserID(), model.NewMobilePhone);
                        return View("ChangeRequestSuccess", (object)model.NewMobilePhone);
                    }
                    catch (ValidationException ex)
                    {
                        ModelState.AddModelError("", ex.Message);
                    }
                }
            }

            if (button == "remove")
            {
                this.userAccountService.RemoveMobilePhone(User.GetUserID());
                return View("Success");
            }

            var acct = this.authSvc.UserAccountService.GetByID(User.GetUserID());
            model.Current = acct.MobilePhoneNumber;
            return View("Index", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Confirm(ChangeMobileFromCodeInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (this.userAccountService.ChangeMobilePhoneFromCode(this.User.GetUserID(), model.Code))
                    {
                        // since the mobile had changed, reissue the 
                        // cookie with the updated claims
                        authSvc.SignIn(User.GetUserID());

                        return View("Success");
                    }

                    ModelState.AddModelError("", "Error confirming code.");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View("Confirm", model);
        }
    }
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/ChangeMobile/ChangeRequestSuccess.cshtml
@model string

@{
    ViewBag.Title = "ChangeRequestSuccess";
}

<h2>Success</h2>
<p>
    You should recieve a SMS message shortly at @Model.
    It will contain the code to enter into the confirmation area below.
</p>

@using (Html.BeginForm("Confirm", "ChangeMobile"))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Confirm</legend>
        <p>
            <label for="code">Code</label>
            <input id="code" name="code" />
        </p>
        <p class="buttons"><button>Submit</button></p>
    </fieldset>
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/ChangeMobile/Confirm.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.ChangeMobileFromCodeInputModel

@{
    ViewBag.Title = "Confirm Mobile Code";
}

@using (Html.BeginForm("Confirm", "ChangeMobile"))
{
    @Html.AntiForgeryToken()

    <fieldset>
    @Html.ValidationSummary()
        <legend>Confirm</legend>
        <p>
            <label for="code">Code</label>
            <input id="code" name="code" />
        </p>
        <p class="buttons"><button>Submit</button></p>
    </fieldset>
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/ChangeMobile/Index.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.ChangeMobileRequestInputModel

@{
    ViewBag.Title = "Change Mobile Phone Number";
}

<h2>@ViewBag.Title</h2>

<h3>Current Mobile: @Model.Current</h3>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("Error")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>

        <p>
            @Html.LabelFor(x=>x.NewMobilePhone)
            @Html.EditorFor(x=>x.NewMobilePhone)
            @Html.ValidationMessageFor(x=>x.NewMobilePhone)
        </p>
        <div class="buttons">
            <button name="button" value="change">Change Mobile Phone Number</button>
            <button name="button" value="remove" class="disable">Remove Mobile Phone Number</button>
        </div>
    </fieldset>
}

@using (Html.BeginForm("Confirm", "ChangeMobile"))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Verify Mobile Code</legend>
        <p>
            <label for="code">Code</label>
            <input id="code" name="code" />
        </p>
        <p class="buttons"><button>Submit</button></p>
    </fieldset>
}

samples/SingleTenantAndNoSql/SingleTenantWebApp/Areas/UserAccount/Views/ChangeMobile/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>
<p>You mobile number was successfully changed.</p>